# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1525853121);
user_pref("app.update.lastUpdateTime.background-update-timer", 1525853361);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1525853241);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1525852881);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1525853001);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.search.countryCode", "VN");
user_pref("browser.search.region", "VN");
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.slowStartup.averageTime", 1189);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20180327191532");
user_pref("browser.startup.homepage_override.mstone", "3.4.2");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":0}");
user_pref("browser.taskbar.lastgroupid", "3E917604E7C33D56");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"moonttool@Off.JustOff\":{\"version\":\"1.1.4\",\"type\":\"extension\",\"descriptor\":\"C:\\\\Users\\\\lvc\\\\AppData\\\\Roaming\\\\Moonchild Productions\\\\Pale Moon\\\\Profiles\\\\x3t85q0n.Default User\\\\extensions\\\\moonttool@Off.JustOff.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:27.8.3");
user_pref("extensions.lastAppVersion", "27.8.3");
user_pref("extensions.lastPlatformVersion", "3.4.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.update.autoUpdateDefault", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Program Files (x86)\\\\Pale Moon\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"27.8.3\",\"st\":1524714736433,\"mt\":1522180167000}},\"app-profile\":{\"moonttool@Off.JustOff\":{\"d\":\"C:\\\\Users\\\\lvc\\\\AppData\\\\Roaming\\\\Moonchild Productions\\\\Pale Moon\\\\Profiles\\\\x3t85q0n.Default User\\\\extensions\\\\moonttool@Off.JustOff.xpi\",\"e\":true,\"v\":\"1.1.4\",\"st\":1525853622586}}}");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("image.http.accept", "image/webp,image/jxr,image/png,image/*;q=0.8,*/*;q=0.5");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("status4evar.firstRun", false);
user_pref("status4evar.migration", 8);
user_pref("toolkit.startup.last_success", 1525852760);
user_pref("toolkit.telemetry.previousBuildID", "20180327191532");
